### ISSUE TITLE
How to version the specification and what version of what runtime are supported

### ISSUE THREAD

**Issue by seebees** [awslabs/aws-encryption-sdk-specification#104]
Now that we have a specification,
as this will change how is this change tracked.
Also, what versions do individual ESDK support
and how is this tested and maintained?

**Comment by mattsb42-aws** [comment]
note: we are currently versioning each spec feature doc independently. I think that for most features this is the correct way to go, because most of them are independent of each other (ex: the AWS KMS keyring doesn't really have anything to do with the message format).

Most of the current docs are versioned as `0.1.0-preview`, but we do not define a versioning policy.

I propose that we:

1. Determine what `1.0.0` means for the spec and features.
1. Once we hit `1.0.0`, follow Semantic Versioning.
1. While we are in `0.Y.Z`, allow breaking changes in `Y` increments.

**Comment by mattsb42-aws** [comment]
Another thing to call out in this issue, as discussed here[1]: where/how should we record which compatibility matrices between spec documents and implementations?

[1] https://github.com/awslabs/aws-encryption-sdk-specification/pull/105#discussion_r429357865
